name: Update Feature Flag

on:
  push:
    branch:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  Feature_Flag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get existing config from yml
        run: |
          yq eval 'to_entries[] | "\(.key):\(.value | tojson)"' ./MyProject/details.yml
      - name: Get existing Feature Flags
        env:
          GROWTHBOOK_API_KEY: ${{ secrets.FEATURE_FLAG_API_KEY }}
        run: |
          curl https://api.growthbook.io/api/v1/features \
            -H "Authorization: Bearer $GROWTHBOOK_API_KEY" \
            -H "Content-Type: application/json"
      - name: Update existing Feature Flags
        env:
          GROWTHBOOK_API_KEY: ${{ secrets.FEATURE_FLAG_API_KEY }}
        run: |
          list=$(yq eval 'to_entries[] | "\(.key):\(.value | tojson)"' ./MyProject/details.yml | sed 's/.*{//')
          echo $list | jq -r 'keys[]
          # for feature in $(echo "$list" | jq -r 'keys[]'); do
          #   value=$(echo "$list" | jq -r ".$feature")
          #   echo $feature
          #   echo $value
          #   # curl -X POST "https://api.growthbook.io/api/v1/features/$feature" \
          #   #   -H "Authorization: Bearer $GROWTHBOOK_API_KEY" \
          #   #   -H "Content-Type: application/json" \
          #   #   -d "{\"defaultValue\": \"$value\"}"
          # done
